name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liuCUtf8Gwscn2Da"
GITHUB_OWNER = "BGdongdong"
GITHUB_REPO = "wahaha-nav"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://wahaha-nav.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://wahaha-nav.pages.dev/"

